"""Sparse semantic encoding module."""

from .sparse_ternary import (
    SparseVector,
    HadamardBasis,
    BIPOLAR_PAIRS,
    BipolarPair,
    SentenceScaleBasis,
    encode_word_full,
    create_informational_zero,
    create_sentence_basis,
    bind,
    bundle,
    permute,
    generate_role_pattern,
)
from .semantic_dimensions import (
    D,
    N_DIMENSIONS,
    DIMS_PER_DIMENSION,
    SemanticDimension,
    BIPOLAR_PAIRS, # This is now imported from sparse_ternary, but kept here for backward compatibility or if it's a different object. Assuming it's the same and should be removed.
    BipolarPair, # This is now imported from sparse_ternary, but kept here for backward compatibility or if it's a different object. Assuming it's the same and should be removed.
    DIMENSION_NAMES,
    PrimitiveInfo,
    PRIMITIVE_REGISTRY,
    HierarchyLevel,
    QUANTITY_HIERARCHY,
    INTENSITY_HIERARCHY,
    CERTAINTY_HIERARCHY,
    is_bipolar,
    get_bipolar_pair,
    get_canonical_pole,
    SEMANTIC_ROLES,
    Scale,
    SentenceBank,
    SENTENCE_PRIMITIVES,
    SentencePrimitiveInfo,
    SENTENCE_PRIMITIVE_REGISTRY,
    COMP_METADATA,
    TextBank,
    TEXT_PRIMITIVES,
    ParagraphBank,
    PARAGRAPH_PRIMITIVES,
    is_compositional_operator,
    get_compositional_metadata,
)

__all__ = [
    "SparseVector",
    "HadamardBasis",
    "BIPOLAR_PAIRS",
    "BipolarPair",
    "SentenceScaleBasis",
    "encode_word_full",
    "create_informational_zero",
    "create_sentence_basis",
    "bind",
    "bundle",
    "permute",
    "generate_role_pattern",
    "D",
    "N_DIMENSIONS",
    "DIMS_PER_DIMENSION",
    "SemanticDimension",
    "BIPOLAR_PAIRS",
    "DIMENSION_NAMES",
    "PrimitiveInfo",
    "PRIMITIVE_REGISTRY",
    "SEMANTIC_ROLES",
    "Scale",
    "SentenceBank",
    "SENTENCE_PRIMITIVES",
    "SentencePrimitiveInfo",
    "SENTENCE_PRIMITIVE_REGISTRY",
    "COMP_METADATA",
    "TextBank",
    "TEXT_PRIMITIVES",
    "ParagraphBank",
    "PARAGRAPH_PRIMITIVES",
    "is_compositional_operator",
    "get_compositional_metadata",
]
